<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="MVTec.HalconDotNet-Windows" Version="24111.0.0" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MvCameraControl.Net">
      <HintPath>..\..\..\Halcon_Study\Hivision\Hivision\DLL\MvCameraControl.Net.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>